"""
Django settings for ohc_time_attendance project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _desktop_runtime_dir() -> Path:
    configured = os.getenv("ATTENDANCE_DESKTOP_DATA_DIR")
    if configured:
        root = Path(configured)
    elif os.getenv("ATTENDANCE_DESKTOP_MODE") == "1" or getattr(sys, "frozen", False):
        root = Path(os.getenv("LOCALAPPDATA", str(BASE_DIR))) / "TimeAndAttendance"
    else:
        root = BASE_DIR
    root.mkdir(parents=True, exist_ok=True)
    return root


RUNTIME_DIR = _desktop_runtime_dir()
RUNTIME_MEDIA_DIR = RUNTIME_DIR / "media"
RUNTIME_MEDIA_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b%dojd@n&=@*ca+^+w#g5gcoz8w3(rk#%amn0-ip_v%4x%ws$d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

MEDIA_URL = '/media/'
MEDIA_ROOT = str(RUNTIME_MEDIA_DIR)


# Application definition

INSTALLED_APPS = [
    'churchOffice',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ohc_time_attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ohc_time_attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': RUNTIME_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

ATTENDANCE_API_BASE_URL = os.getenv(
    "ATTENDANCE_API_BASE_URL",
    "https://heavensconnect.onrender.com/api/attendance",
)
ATTENDANCE_API_TOKEN = os.getenv("ATTENDANCE_API_TOKEN", "")
ATTENDANCE_API_TIMEOUT = int(os.getenv("ATTENDANCE_API_TIMEOUT", "30"))
ATTENDANCE_API_VERIFY_SSL = os.getenv("ATTENDANCE_API_VERIFY_SSL", "True") == "True"
TIME_ATTENDANCE_DOWNLOAD_URL = os.getenv(
    "TIME_ATTENDANCE_DOWNLOAD_URL",
    "https://github.com/sylvicruza/FacialRecognitionSystem/releases/latest",
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.openedheavenschapel.co.uk"
EMAIL_PORT = 587
EMAIL_HOST_USER = "welfare@openedheavenschapel.co.uk"
EMAIL_HOST_PASSWORD = "Ifeanyi/1000"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = "welfare@openedheavenschapel.co.uk"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
DEMO_REQUEST_EMAIL = os.getenv("DEMO_REQUEST_EMAIL", EMAIL_HOST_USER)
