# Generated by Django 5.2 on 2025-04-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portal_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_images/')),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
    ]
