# Generated by Django 5.2 on 2025-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchOffice', '0002_cameraconfiguration_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nfc_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
