# Generated by Django 5.2 on 2026-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchOffice', '0003_person_nfc_uid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('person', 'date'), name='uniq_attendance_person_date'),
        ),
    ]
