# Generated by Django 5.2 on 2026-03-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchOffice', '0004_attendance_uniq_attendance_person_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='churchOffice.cameraconfiguration'),
        ),
    ]
